language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
install:
- dotnet restore
script:
- dotnet build
- dotnet test C:\Users\Casper\Desktop\School\3. Semester\SDM\TravisRepository/TravisRepository.csproj
branches:
  only:
  - master
  - development